/**
 * lib/validators.js — Pure document validators (no I/O).
 *
 * Extracted from cli/validate-documents.js to break the layering inversion
 * where server/validator.js (LSP runtime) depended on the CLI orchestrator.
 *
 * All functions here are pure (no filesystem access). CONFIG is included
 * because it is consumed exclusively by these pure validators — the CLI
 * re-imports and re-exports it from here.
 *
 * Consumers:
 *   - cli/validate-documents.js  (imports + re-exports for backward compat)
 *   - server/validator.js        (imports pure validators directly)
 */

import { relative } from 'path';
import { loadVaultConfig } from './vault-config.js';
import { findSectionRuleBlocks } from './template-section-rules.js';

// Configuration. Per-doc-type rules (required fields, allowed statuses, state
// transitions, path shape) live in each template's `fields:` schema block —
// load via `loadTemplateRules(frontmatter.template)`. This object owns only
// the cross-cutting concerns that span every template: which folders to scan,
// which to exclude, slug naming, and template-meta-leak detection.
//
// `contentFolders` and `excludePatterns` are vault-agnostic atoms resolved
// lazily from lib/vault-config.js (`.claude/vault-keeper.json` overrides the
// defaults). They are getters so each call site picks up the active project
// root (the CLI chdir's to it before any scan).
const CONFIG = {
  get contentFolders() {
    return loadVaultConfig().vaultFolders;
  },
  templateFolder: 'templates',
  get excludePatterns() {
    return loadVaultConfig().excludePatterns;
  },

  // Frontmatter fields that belong to TEMPLATES only and must be stripped
  // when they leak into derived instances via copy-paste authoring.
  //
  // EXCLUDED from this list:
  //   - `template` (singular): REQUIRED in instances — stripping would break
  //     every instance.
  //   - `template_path`: overloaded — folder-readme docs use it legitimately
  //     to document which template files in the folder belong to.
  templateOnlyFields: [
    'fields',
    'strict',
    'sections',
    'tier',
    'template_version',
    'template_id',
  ],

  // Slug naming rule applies to every folder segment and every file basename
  // within content folders (and templates/). Filesystem paths feed into URLs,
  // search indexes, git refs, shell completion, and command-line tools —
  // spaces / uppercase / underscores break those surfaces. Forcing
  // lowercase-kebab-case keeps the path layer consistent.
  //
  // The exempt lists cover well-known conventions (README.md from open-source
  // norms, DESIGN.md from Google Labs, CLAUDE.md from Claude Code, etc.).
  slug: {
    // Each path segment (folder OR file basename) and each dot-separated
    // part of a file basename must match this pattern:
    //   - lowercase ASCII letters + digits + hyphen
    //   - no leading/trailing hyphen
    //   - no consecutive hyphens (the alternating form forbids them)
    segmentPattern: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,

    // Task-ID prefix is an INTENTIONAL exception. Files in tasks/ folders are
    // generated by `task.create` (see task-lib.js TASK_CATALOGS) using the
    // shape `<PREFIX>-<NUMBER>-<slug>.md` where PREFIX is lowercase by
    // project convention (t = technical, d = design). Note: this pattern is
    // technically redundant with segmentPattern (lowercase task IDs already
    // match it) — kept as an explicit assertion of the task-ID shape contract.
    taskIdPattern: /^[a-z]+-\d+-[a-z0-9]+(?:-[a-z0-9]+)*$/,

    // Full file basenames (with extension) that bypass the slug rule.
    // Universal conventions used by tooling (npm, GitHub, Claude Code, Google
    // Labs) — renaming would break muscle-memory and external integrations.
    exemptBasenames: [
      'README.md',
      'BOARD.md',
      'CLAUDE.md',
      'MEMORY.md',
      'LICENSE',
      'LICENSE.md',
      'CHANGELOG.md',
      'CONTRIBUTING.md',
      'DESIGN.md',     // Google Labs DESIGN.md spec format
      'AGENTS.md',     // oh-my-claudecode multi-agent convention
    ],

    // Folder segments that bypass the slug rule. Hidden folders (`.omc`,
    // `.claude`, `.specify`, `.git`) start with `.` — already exempted by
    // the dotfile branch in validateSlug. Add named exceptions here only
    // when a folder must keep a non-slug name (none currently needed).
    exemptFolders: [],
  },
};

// ── Pure validators ───────────────────────────────────────────────────────

/**
 * Infer document type from frontmatter.
 */
function inferDocType(frontmatter) {
  if (frontmatter?.document_type) return frontmatter.document_type;
  const tpl = frontmatter?.template;
  if (typeof tpl === 'string') {
    const m = tpl.match(/templates\/(?:.*\/)?([^/]+?)(?:-template)?\.md$/);
    if (m) return m[1];
  }
  return 'unknown';
}

/**
 * Detect if a file is a template (scaffold with placeholders).
 *
 * Templates live in CONFIG.templateFolder and contain placeholder values
 * like "YYYY-MM-DD", "[Title]", "[@handle]" that are NOT valid content.
 * They are intentionally skipped during content validation. Their
 * `fields:` frontmatter block is meta-schema for derived instances,
 * not a self-validation contract.
 */
function isTemplateFile(filepath) {
  const folder = CONFIG.templateFolder;
  return filepath.startsWith(`${folder}/`) ||
         filepath.includes(`/${folder}/`) ||
         filepath === folder;
}

/**
 * Decide whether a filepath is a template-derived INSTANCE (not the scaffold).
 *
 * Pure path-based check — inverted version of isTemplateFile(). Templates live
 * in `templates/` and own the meta-schema fields (`fields:` etc.);
 * everything else is an instance and must NOT carry those fields.
 */
function isTemplateInstance(filepath) {
  if (!filepath) return false;
  if (filepath.startsWith('templates/')) return false;
  if (filepath.includes('/templates/')) return false;
  return true;
}

/**
 * Identify template-only fields that have leaked into an instance's
 * frontmatter via copy-paste from a template scaffold. Pure: no I/O.
 *
 * Returns list of leaked field names (subset of CONFIG.templateOnlyFields).
 * Returns [] for templates themselves and for clean instances.
 */
function findTemplateMetaLeaks(filepath, frontmatter) {
  if (!isTemplateInstance(filepath)) return [];
  if (!frontmatter || typeof frontmatter !== 'object') return [];
  return CONFIG.templateOnlyFields.filter((field) => field in frontmatter);
}

/**
 * Validate template field
 */
function validateTemplateField(frontmatter, filepath) {
  const issues = [];

  if (!frontmatter.template) {
    issues.push({
      level: 'error',
      field: 'template',
      message: 'Missing required template field',
      fix: 'Add template: "templates/[template-name].md" to frontmatter'
    });
  } else if (!frontmatter.template.startsWith('templates/')) {
    issues.push({
      level: 'error',
      field: 'template',
      message: `Invalid template path: ${frontmatter.template}`,
      fix: 'Template path must start with "templates/"'
    });
  } else if (!frontmatter.template.endsWith('.md')) {
    issues.push({
      level: 'error',
      field: 'template',
      message: 'Template path must end with .md',
      fix: `Change to: ${frontmatter.template}.md`
    });
  }

  return issues;
}


/**
 * Detect template-only fields that have leaked into an instance via
 * copy-paste from a template scaffold. Reported as warnings (non-fatal but
 * actionable — the instance is still readable, just carries dead metadata).
 *
 * Confidence: HIGH. Rule is canonical (CONFIG.templateOnlyFields), no inference.
 */
function validateTemplateMetaLeak(frontmatter, filepath) {
  const leaks = findTemplateMetaLeaks(filepath, frontmatter);
  return leaks.map((field) => ({
    level: 'warning',
    field,
    message: `Template-only field "${field}" leaked into instance from template scaffold`,
    fix: `Remove "${field}:" from frontmatter — it belongs to templates/ only`,
  }));
}

/**
 * Suggest a slug form for a non-conforming name. Pure helper used by
 * validateSlug to produce actionable fix hints.
 *
 *   "TrueProfit tone and voice"     → "trueprofit-tone-and-voice"
 *   "syncStartHandler"              → "sync-start-handler"
 *   "design_tokens"                 → "design-tokens"
 *   "SHTP-6138-cogs"                → "shtp-6138-cogs"
 *
 * Strategy:
 *   1. Insert a `-` between a lowercase/digit and an uppercase letter
 *      (camelCase → camel-Case).
 *   2. Replace runs of underscores / whitespace with `-`.
 *   3. Lowercase everything.
 *   4. Strip any character that isn't [a-z0-9-].
 *   5. Collapse repeated `--` and trim leading/trailing `-`.
 *
 * Returns "" when the input has no slug-able characters at all (caller
 * should fall back to a generic message).
 */
function suggestSlug(name) {
  if (typeof name !== 'string' || !name) return '';
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')   // camelCase → camel-Case
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2') // ABCFoo → ABC-Foo
    .replace(/[_\s]+/g, '-')                   // _ or whitespace → -
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '')                // strip non-slug chars
    .replace(/-+/g, '-')                       // collapse ---
    .replace(/^-|-$/g, '');                    // trim ends
}

/**
 * Validate that every folder segment and the file basename conform to the
 * slug convention (lowercase ASCII letters / digits / hyphens, no spaces, no
 * uppercase, no underscores). Reported as ERRORS — non-slug paths break
 * URLs, grep workflows, shell completion, and CI ref names.
 *
 * Rules:
 *   - Folder segments must match CONFIG.slug.segmentPattern OR appear in
 *     CONFIG.slug.exemptFolders. Hidden folders (segment starts with `.`)
 *     are tooling artifacts (`.git`, `.omc`, `.claude`) and skipped.
 *   - File basename: the part before the FIRST `.` must match either
 *     segmentPattern OR taskIdPattern (e.g. `t-051-foo`). Every subsequent
 *     extension segment must match segmentPattern. Hidden files (`.gitkeep`,
 *     `.gitignore`) are exempt. Well-known basenames (README.md, BOARD.md,
 *     DESIGN.md, etc.) are exempt.
 *
 * The check is path-based and pure — no file I/O.
 */
function validateSlug(filepath) {
  const issues = [];
  if (!filepath || typeof filepath !== 'string') return issues;

  // Normalize to repo-relative form so the host-absolute prefix
  // (`/Users/.../<repo>/`) doesn't get slug-validated. Absolute → relative
  // via path.relative; leading `./` is stripped uniformly.
  let rel = filepath.startsWith('/')
    ? relative(process.cwd(), filepath)
    : filepath;
  rel = rel.replace(/^\.\//, '');
  if (!rel || rel.startsWith('..')) return issues;

  const segments = rel.split('/').filter(Boolean);
  if (segments.length === 0) return issues;

  const lastIdx = segments.length - 1;
  const { segmentPattern, taskIdPattern, exemptBasenames, exemptFolders } = CONFIG.slug;

  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];

    // Hidden folder/file (`.git`, `.gitkeep`) → tooling artifact, skip.
    if (seg.startsWith('.')) continue;

    const isFile = i === lastIdx;

    if (!isFile) {
      // Folder segment.
      if (segmentPattern.test(seg)) continue;
      if (exemptFolders.includes(seg)) continue;
      const suggested = suggestSlug(seg);
      issues.push({
        level: 'error',
        field: 'folder',
        message: `Folder '${seg}' violates slug convention (lowercase letters, digits, hyphens only)`,
        fix: suggested
          ? `Rename folder to '${suggested}/'`
          : `Rename folder to lowercase-kebab-case`,
      });
      continue;
    }

    // File basename.
    if (exemptBasenames.includes(seg)) continue;

    // Split on FIRST dot to separate name from extension chain.
    // e.g. "tailwind.config.js" → name="tailwind", ext="config.js"
    //      "DESIGN.md"           → name="DESIGN",   ext="md"      (handled by exempt)
    //      "T-051-foo.md"        → name="T-051-foo", ext="md"
    const firstDot = seg.indexOf('.');
    const name = firstDot >= 0 ? seg.slice(0, firstDot) : seg;
    const extChain = firstDot >= 0 ? seg.slice(firstDot + 1) : '';

    const nameOk =
      segmentPattern.test(name) || taskIdPattern.test(name);

    // Every dot-separated extension segment must also be slug-shape.
    let extOk = true;
    let badExtSeg = null;
    if (extChain) {
      for (const part of extChain.split('.')) {
        if (!segmentPattern.test(part)) {
          extOk = false;
          badExtSeg = part;
          break;
        }
      }
    }

    if (nameOk && extOk) continue;

    // Build a fix suggestion: re-slugify the name part, preserve extension chain.
    const suggestedName = suggestSlug(name);
    const fixName = suggestedName || 'renamed';
    const fixBase = extChain ? `${fixName}.${extChain.toLowerCase()}` : fixName;

    if (!nameOk) {
      issues.push({
        level: 'error',
        field: 'filename',
        message: `Filename '${seg}' violates slug convention (lowercase letters, digits, hyphens only)`,
        fix: `Rename to '${fixBase}' (or another lowercase-kebab name)`,
      });
    } else {
      issues.push({
        level: 'error',
        field: 'filename',
        message: `Extension segment '${badExtSeg}' in '${seg}' violates slug convention`,
        fix: `Each dot-separated segment must be lowercase-kebab — e.g. '${name}.${extChain.toLowerCase()}'`,
      });
    }
  }

  return issues;
}

/**
 * Strip code regions from markdown body so prose-level scanners (e.g. the
 * relative-path regex) don't false-positive on documented code samples.
 *
 * Code regions stripped:
 *   - Fenced blocks (``` ... ``` and ~~~ ... ~~~)
 *   - Inline code spans (`...`)
 *   - 4-space-indented code lines (legacy markdown code block syntax)
 *
 * Pure: returns a new string. Used by validatePaths().
 *
 * Why: T-054 documents JS code like `$inline("./fp.js")` inside a 4-space
 * indented block. Without this strip, the regex matches `"./fp.js"` and
 * misclassifies a code path as a vault relative path. The body warning
 * exists to flag broken vault links written as `./foo.md`-style — code
 * documentation is not its target.
 */
function stripCodeRegions(text) {
  if (typeof text !== 'string') return '';
  return text
    .replace(/```[\s\S]*?```/g, '')      // fenced ```
    .replace(/~~~[\s\S]*?~~~/g, '')      // fenced ~~~
    .replace(/`[^`\n]*`/g, '')            // inline `code`
    .replace(/^( {4,}|\t)[^\n]*$/gm, ''); // 4-space / tab indented lines
}

/**
 * Validate paths are absolute
 */
function validatePaths(frontmatter, body) {
  const issues = [];
  const relativePathPattern = /['"](\.\.\/|\.\/)[^'"]+['"]/g;

  // Check frontmatter relationships
  if (frontmatter.relationships) {
    const checkRelationships = (relationships) => {
      for (const [type, items] of Object.entries(relationships)) {
        if (Array.isArray(items)) {
          items.forEach((item, index) => {
            if (item.path && (item.path.startsWith('../') || item.path.startsWith('./'))) {
              issues.push({
                level: 'error',
                field: `relationships.${type}[${index}].path`,
                message: `Relative path found: ${item.path}`,
                fix: 'Use absolute path from project root'
              });
            }
          });
        }
      }
    };
    checkRelationships(frontmatter.relationships);
  }

  // Check body content — strip code regions first so JS/Go code samples like
  // `$inline("./fp.js")` are not flagged as vault relative paths.
  const proseBody = stripCodeRegions(body);
  const matches = proseBody.match(relativePathPattern);
  if (matches) {
    issues.push({
      level: 'warning',
      field: 'body',
      message: `Found ${matches.length} relative path(s) in document body`,
      fix: 'Replace with absolute paths from project root'
    });
  }

  return issues;
}

/**
 * Built-in rule: detect a `yaml section-rules` fenced code block leaking into
 * a document.
 *
 * `section-rules` fences are a template-authoring construct — templates
 * declare per-section validation rules with them (see
 * `lib/template-section-rules.js`). An authored document must never carry
 * one; its presence means a template fragment was copy-pasted into a
 * document. Reported as an error, one issue per offending block.
 *
 * `bodyLine` is the 1-indexed, body-relative line of the offending fence.
 * The CLI ignores it (its report is field + message only); the LSP wrapper
 * maps it to a document-absolute line for an exact editor squiggle.
 *
 * This rule is generic infrastructure, not vault knowledge: the
 * `section-rules` fence is the plugin's own DSL construct, so detecting its
 * misuse needs no vault-specific vocabulary. No template-level constraint can
 * express it — the rule applies to every document regardless of template.
 */
function validateSectionRulesLeak(body) {
  if (typeof body !== 'string' || !body) return [];
  return findSectionRuleBlocks(body).map(({ line }) => ({
    level: 'error',
    field: 'body',
    error_type: 'section-rules-leak',
    message:
      'Delete this "```yaml section-rules" fence — it is a template-only construct that leaked into the document.',
    fix: 'Remove the entire fenced block (from the opening "```yaml section-rules" line through its closing "```") and any rule keys inside. Per-section rules belong in templates/, not in authored documents.',
    bodyLine: line,
  }));
}

export {
  CONFIG,
  inferDocType,
  isTemplateFile,
  isTemplateInstance,
  findTemplateMetaLeaks,
  validateTemplateField,
  validateTemplateMetaLeak,
  suggestSlug,
  validateSlug,
  stripCodeRegions,
  validatePaths,
  validateSectionRulesLeak,
};
